name: Generate Resume PDF

on:
  # allows manual execution of this workflow from the Actions tab
  workflow_dispatch:

  push:
    branches:
      - master

jobs:
  build-pdf:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Install Pandoc and LaTeX engine (XeLaTeX)
      - name: Install Pandoc and LaTeX
        run: sudo apt-get update && sudo apt-get install -y pandoc texlive-xetex

      # Step 3: Generate PDF from index.md
      - name: Generate PDF
        run: pandoc index.md -o resume-mousa.pdf --pdf-engine=xelatex

      # Step 4: Commit PDF back to repository
      - name: Commit PDF
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add resume-mousa.pdf
          git commit -m "Update PDF resume" || echo "No changes to commit"
          git push
